name: GitHub Readme Snake

on:
  schedule:
    - cron: '0 * * * *' # Her saat çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake Graph
        uses: ileriayo/gh-profile-snake-action@v1
        with:
          file: snake.svg
          username: FatihKarabulut
      - name: Commit SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake.svg
          git commit -m "Update snake graph" || echo "No changes to commit"
          git push
